### ISSUE TITLE
If the mermaid is rendered via DataviewJS, the pop-up would be doubled

### ISSUE THREAD

**Issue by Moyf** [gitcpy/obsidian-mermaid-pop#1]
If I use dataviewJS to render the mermaid, there would be TWO pop-ups:
![173e332c-a378-4c9f-9358-43bae72c95ff](https://github.com/user-attachments/assets/61bba87b-3932-4262-b1b6-47645783906b)

⬇️ You can use this codeblock to test ;)

````md

```dataviewjs
let ganttContent = `\`\`\`mermaid
gantt
  title Today Gantt
  dateFormat YYYY-MM-dd HH:mm
  axisFormat %H:%M
  tickInterval 2hour

  test: 2024-10-01 08:20, 1d
\`\`\``;

dv.span(ganttContent);
```

````

> This is a DataviewJS block, which uses the [Dataview](https://blacksmithgu.github.io/obsidian-dataview/) plugin

___

BTW, maybe use css var to adapt to both dark and light themes?
Now in Dark Theme the color would be hard to see:
![image](https://github.com/user-attachments/assets/57e54683-b615-4acd-b537-f20a08688ea4)

But after using `var()`, for example:

```css
.control-button {
    color: var(--text-normal)
}
```

Then the button would just inherit the text's color:
![image](https://github.com/user-attachments/assets/572741b7-73c5-4731-a80e-fd0e17028b2f)

**Comment by gitcpy** [comment]
Thanks for you advices. I will make some updates in the future. May be next month. Hope not long.

**Comment by Moyf** [comment]
> Thanks for you advices. I will make some updates in the future. May be next month. Hope not long.

Yay, no problem and take your time! Thank you for developing this useful plugin  <3

**Comment by gitcpy** [comment]
I have fixed the bug double popups in release 0.2.19. 
Just try it.

**Comment by Moyf** [comment]
> I have fixed the bug double popups in release 0.2.19. Just try it.

So quick! Thank you!
I've updated and it's fixed! Brilliant!

**Comment by Moyf** [comment]
嗨，我这边又稳定复现了，我录制了一个 Debugging 断点视频：


https://github.com/user-attachments/assets/2e05c732-caf4-4f02-8650-ecb3acb629d7


___

以及这是刷新页面时注册事件的断点：
https://github.com/user-attachments/assets/225823f5-f865-463c-914d-c243606c9713

可以看到似乎还是注册了两次……

（猜测是不是这里的属性没来得及加上，所以还是重复注册了？

```js
              // 确保每次只绑定一次事件
              if (!markdownView.contentEl.hasAttribute('data-mermaid-popup-bound')) {
                  this.registerMermaidPopup(markdownView.contentEl);
                  markdownView.contentEl.setAttribute('data-mermaid-popup-bound', 'true');
              }
```

以及，鉴于通常情况下**不会有两个 Popup 窗口同时存在**，作为兜底解决方案的话，能不能插件里面记录一下「是否有 Popup 窗口已打开」，并且在有窗口打开的时候，避免打开新的窗口？

我尝试阅读源代码但是没太看懂，所以只能又来提反馈了 > <

**Comment by gitcpy** [comment]
我还没看你的视频，但是我的代码就是按照你说的做的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-mermaid-pop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月20日(星期五) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/obsidian-mermaid-pop] If the mermaid is rendered via DataviewJS, the pop-up would be doubled (Issue #1)





 
嗨，我这边又稳定复现了，我录制了一个 Debugging 断点视频：
 
https://github.com/user-attachments/assets/2e05c732-caf4-4f02-8650-ecb3acb629d7
 
 
以及这是刷新页面时注册事件的断点：
 https://github.com/user-attachments/assets/225823f5-f865-463c-914d-c243606c9713
 
可以看到似乎还是注册了两次……
 
（猜测是不是这里的属性没来得及加上，所以还是重复注册了？
               // 确保每次只绑定一次事件               if (!markdownView.contentEl.hasAttribute('data-mermaid-popup-bound')) {                   this.registerMermaidPopup(markdownView.contentEl);                   markdownView.contentEl.setAttribute('data-mermaid-popup-bound', 'true');               }
 
以及，鉴于通常情况下不会有两个 Popup 窗口同时存在，作为兜底解决方案的话，能不能插件里面记录一下「是否有 Popup 窗口已打开」，并且在有窗口打开的时候，避免打开新的窗口？
 
我尝试阅读源代码但是没太看懂，所以只能又来提反馈了 &gt; <

**Comment by gitcpy** [comment]
我还没看你的视频，但是我的代码就是按照你说的做的, 我等下查看一下




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "gitcpy/obsidian-mermaid-pop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月20日(星期五) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/obsidian-mermaid-pop] If the mermaid is rendered via DataviewJS, the pop-up would be doubled (Issue #1)





 
嗨，我这边又稳定复现了，我录制了一个 Debugging 断点视频：
 
https://github.com/user-attachments/assets/2e05c732-caf4-4f02-8650-ecb3acb629d7
 
 
以及这是刷新页面时注册事件的断点：
 https://github.com/user-attachments/assets/225823f5-f865-463c-914d-c243606c9713
 
可以看到似乎还是注册了两次……
 
（猜测是不是这里的属性没来得及加上，所以还是重复注册了？
               // 确保每次只绑定一次事件               if (!markdownView.contentEl.hasAttribute('data-mermaid-popup-bound')) {                   this.registerMermaidPopup(markdownView.contentEl);                   markdownView.contentEl.setAttribute('data-mermaid-popup-bound', 'true');               }
 
以及，鉴于通常情况下不会有两个 Popup 窗口同时存在，作为兜底解决方案的话，能不能插件里面记录一下「是否有 Popup 窗口已打开」，并且在有窗口打开的时候，避免打开新的窗口？
 
我尝试阅读源代码但是没太看懂，所以只能又来提反馈了 &gt; <

**Comment by gitcpy** [comment]
你查看一下视频，我这边没复现，现在确认一下你删除创建重装了吗？
步骤：删除插件，brat删除，，然后还有brat还有一个确认按钮，关闭ob，可能缓存等原因，可能你需要重复约2-3次，我甚至试过重复5-6次，不知道是brat的问题还是ob问题，你得多试试，非常感谢你的使用和反馈！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-mermaid-pop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月20日(星期五) 下午2:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/obsidian-mermaid-pop] If the mermaid is rendered via DataviewJS, the pop-up would be doubled (Issue #1)





 
嗨，我这边又稳定复现了，我录制了一个 Debugging 断点视频：
 
https://github.com/user-attachments/assets/2e05c732-caf4-4f02-8650-ecb3acb629d7
 
 
以及这是刷新页面时注册事件的断点：
 https://github.com/user-attachments/assets/225823f5-f865-463c-914d-c243606c9713
 
可以看到似乎还是注册了两次……
 
（猜测是不是这里的属性没来得及加上，所以还是重复注册了？
               // 确保每次只绑定一次事件               if (!markdownView.contentEl.hasAttribute('data-mermaid-popup-bound')) {                   this.registerMermaidPopup(markdownView.contentEl);                   markdownView.contentEl.setAttribute('data-mermaid-popup-bound', 'true');               }
 
以及，鉴于通常情况下不会有两个 Popup 窗口同时存在，作为兜底解决方案的话，能不能插件里面记录一下「是否有 Popup 窗口已打开」，并且在有窗口打开的时候，避免打开新的窗口？
 
我尝试阅读源代码但是没太看懂，所以只能又来提反馈了 &gt; <

**Comment by Moyf** [comment]
> 你查看一下视频，我这边没复现，现在确认一下你删除创建重装了吗？ 步骤：删除插件，brat删除，，然后还有brat还有一个确认按钮，关闭ob，可能缓存等原因，可能你需要重复约2-3次，我甚至试过重复5-6次，不知道是brat的问题还是ob问题，你得多试试，非常感谢你的使用和反馈！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gitcpy/obsidian-mermaid-pop" ***@***.***&gt;; 发送时间:&nbsp;2024年9月20日(星期五) 下午2:52 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gitcpy/obsidian-mermaid-pop] If the mermaid is rendered via DataviewJS, the pop-up would be doubled (Issue #1) 嗨，我这边又稳定复现了，我录制了一个 Debugging 断点视频： https://github.com/user-attachments/assets/2e05c732-caf4-4f02-8650-ecb3acb629d7 以及这是刷新页面时注册事件的断点： https://github.com/user-attachments/assets/225823f5-f865-463c-914d-c243606c9713 可以看到似乎还是注册了两次…… （猜测是不是这里的属性没来得及加上，所以还是重复注册了？ // 确保每次只绑定一次事件 if (!markdownView.contentEl.hasAttribute('data-mermaid-popup-bound')) { this.registerMermaidPopup(markdownView.contentEl); markdownView.contentEl.setAttribute('data-mermaid-popup-bound', 'true'); } 以及，鉴于通常情况下不会有两个 Popup 窗口同时存在，作为兜底解决方案的话，能不能插件里面记录一下「是否有 Popup 窗口已打开」，并且在有窗口打开的时候，避免打开新的窗口？ 我尝试阅读源代码但是没太看懂，所以只能又来提反馈了 &gt; < — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的，我完全卸载重装试试，感谢回复！

**Comment by Moyf** [comment]
我这边有用 Git 管理仓库，尝试「BRAT内删除->删除插件文件夹->重启OB->重新用 BRAT安装」之后查看文件变动，代码是没有区别的，所以之前的应该也已经是新版了。
至于缓存的话，这个不好确定……我修改代码之后重启 OB，它是有新的功能的。

___

然后刚才试了一下，这样调整的话我本地可以 work：
![image](https://github.com/user-attachments/assets/d8c6414e-9ec2-4609-8de2-c704b3d07794)
![image](https://github.com/user-attachments/assets/ce98900b-ece2-4e40-b21b-288078b6b432)

（Sorry，截图示意一下）

但没有进一步测试，所以还不确定会不会造成其它问题。

**Comment by gitcpy** [comment]
还是那句多试，我遇到最离谱的bug是：代码是新的，但是运行的是旧。。。调试对不上代码行。。。bug还在。。。没经验的，完全无法调试下去。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-mermaid-pop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月20日(星期五) 下午3:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/obsidian-mermaid-pop] If the mermaid is rendered via DataviewJS, the pop-up would be doubled (Issue #1)





 
我这边有用 Git 管理仓库，尝试「BRAT内删除-&gt;删除插件文件夹-&gt;重启OB-&gt;重新用 BRAT安装」之后查看文件变动，代码是没有区别的，所以之前的应该也已经是新版了。
 至于缓存的话，这个不好确定……我修改代码之后重启 OB，它是有新的功能的。
 
 
然后刚才试了一下，这样调整的话我本地可以 work：
 image.png (view on web)
 image.png (view on web)
 
（Sorry，截图示意一下）
 
但没有进一步测试，所以还不确定会不会造成其它问题。

**Comment by Moyf** [comment]
> 还是那句多试，我遇到最离谱的bug是：代码是新的，但是运行的是旧。。。调试对不上代码行。。。bug还在。。。没经验的，完全无法调试下去。。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gitcpy/obsidian-mermaid-pop" ***@***.***&gt;; 发送时间:&nbsp;2024年9月20日(星期五) 下午3:41 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gitcpy/obsidian-mermaid-pop] If the mermaid is rendered via DataviewJS, the pop-up would be doubled (Issue #1) 我这边有用 Git 管理仓库，尝试「BRAT内删除-&gt;删除插件文件夹-&gt;重启OB-&gt;重新用 BRAT安装」之后查看文件变动，代码是没有区别的，所以之前的应该也已经是新版了。 至于缓存的话，这个不好确定……我修改代码之后重启 OB，它是有新的功能的。 然后刚才试了一下，这样调整的话我本地可以 work： image.png (view on web) image.png (view on web) （Sorry，截图示意一下） 但没有进一步测试，所以还不确定会不会造成其它问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

哈……哈……哈……好的……
