### ISSUE TITLE
[FR] Adding option for mouse Modifier

### ISSUE THREAD

**Issue by Moyf** [gitcpy/obsidian-mermaid-pop#3]
Hello, could you consider adding an option in Plugin's Setting, to change the "Open Pop-up" method?

For example, now it uses "Mouse Left Button", I hope to use "Ctrl + Mouse Left Button".

---

Kind of like the settings of "Image Toolkit" Plugin:
![image](https://github.com/user-attachments/assets/a3db4733-600a-4780-9e57-860e3bf54f41)

> Just a suggestion, and absolutely no pressure for it, you could decide if it's necessary !

**Comment by gitcpy** [comment]
Added.
