### ISSUE TITLE
[FR] Add support for "Initial Zoom Ratio"

### ISSUE THREAD

**Issue by Moyf** [gitcpy/obsidian-mermaid-pop#5]
Hi！可否添加一个设置选项，支持默认的放大倍率呢？

![image](https://github.com/user-attachments/assets/afacaed5-568e-4f66-9a60-ef3142a32f78)

我之前在本地修改过这个，但是如果有插件设置的话会更方便！

**Comment by gitcpy** [comment]
已经添加，请更新到 0.2.51， 谢谢使用及反馈！

**Comment by gitcpy** [comment]
我修改了插件名字为 Diagram Popup.
现在正在官方审核中，通过后才能下载。
目前只能通过 Brat 下载， 地址是：https://github.com/gitcpy/obsidian-diagram-pop

**Comment by Moyf** [comment]
> 我修改了插件名字为 Diagram Popup. 现在正在官方审核中，通过后才能下载。 目前只能通过 Brat 下载， 地址是：https://github.com/gitcpy/obsidian-diagram-pop

更新了！
![image](https://github.com/user-attachments/assets/49e4c090-8f2a-463b-ba85-454d3c8929a4)
请问怎么设置初始的放大倍率呢？

**Comment by gitcpy** [comment]
"zoom rate" 这个就是啊。。。有三个选项0.1，0.2，0.3，基本够用

**Comment by Moyf** [comment]
> "zoom ratio" 这个就是啊。。。有三个选项0.1，0.2，0.3，基本够用，试试

噢……我想大概有一些误会。
这个我尝试了，是指【缩放的 step】对吧，比如说设成 0.3，那么每次放大都是 +0.3 倍，两下滚轮变成 1.6 倍。

实际上我想设置的是 **弹出时候的放大倍率**——是 Initial Pop Zoom 「初始显示的缩放比例」，而不是「每次缩放操作的倍率」。

（比如默认是 1.0，如果我设成 2.0，就是弹出的时候直接作为2倍大小显示，不用我再去滚动缩放）

**Comment by gitcpy** [comment]
兄弟以后更新了^=^


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/obsidian-diagram-pop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月29日(星期天) 晚上11:15
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [gitcpy/obsidian-diagram-pop] [FR] Add support for "Initial Zoom Ratio" (Issue #5)





  
"zoom ratio" 这个就是啊。。。有三个选项0.1，0.2，0.3，基本够用，试试
  
噢……我想大概有一些误会。
 这个我尝试了，是指【缩放的 step】对吧，比如说设成 0.3，那么每次放大都是 +0.3 倍，两下滚轮变成 1.6 倍。
 
实际上我想设置的是 弹出时候的放大倍率——是 Initial Pop Zoom 「初始显示的缩放比例」，而不是「每次缩放操作的倍率」。
 
（比如默认是 1.0，如果我设成 2.0，就是弹出的时候直接作为2倍大小显示，不用我再去滚动缩放）

**Comment by gitcpy** [comment]
已经添加，更新到 0.2.55
![image](https://github.com/user-attachments/assets/179084be-108d-4986-8abf-58f5fdbd350d)
